###############################################################################
# (c) Copyright 2019 CERN for the benefit of the LHCb Collaboration           #
#                                                                             #
# This software is distributed under the terms of the GNU General Public      #
# Licence version 3 (GPL Version 3), copied verbatim in the file "LICENSE".   #
#                                                                             #
# In applying this licence, CERN does not waive the privileges and immunities #
# granted to it by virtue of its status as an Intergovernmental Organization  #
# or submit itself to any jurisdiction.                                       #
###############################################################################
# This gitlab ci tests, deploys and build the docker images
# It performs some operations with an account.
# Its credentials are stored as secret variable KRB_PASSWORD and KRB_USERNAME
variables:
    DEPLOY_REPO: "lhcb-core/cvmfs-deploy/deploy-lhcbdirac.git"

# Image used for most of the jobs, unless specified
image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7

stages:
  # If there's a new tag, create its tarball, and upload it.
  - release
   # Run all the tests
  - test
  # deploy the coverage results
  - coverage
  - coverageDfs
  # If there's a new tag, build the docker images, and also deploy on CVMFS
  - deploy_release
  - update
  # Left over tasks like tagging the devel container and setting the prod symlink
  - finish_up
  - tag


### test stage ###

# Common configuration between pytest, pylint, pycodestyle
.test_setup: &test_setup
  before_script:
    - yum install -y epel-release
    - yum install -y openssl mysql mysql-libs mysql-devel make ncurses-devel libcurl-devel xz-devel jq swig
    - export PYCURL_SSL_LIBRARY=openssl
     # last version supporting python 2
    - pip install 'setuptools<45'
    - pip install --upgrade 'pip<21'
    - pip install diraccfg virtualenv
    # diracTAG is the DIRAC tag on top of which the latest LHCbDIRAC release is built in releases.cfg
    - lhcbdiracTag=$(cd src && python -c "from LHCbDIRAC import version; print(version)")
    - diracTAG=$(diraccfg as-json src/LHCbDIRAC/releases.cfg | jq -r ".Releases.\"${lhcbdiracTag}\".Depends" | cut -d ':' -f2)
    # Clone the latest LHCbDIRAC
    - echo "Using DIRAC tag $diracTAG"
    - git clone https://github.com/DIRACGrid/DIRAC.git
    - cd DIRAC
    - git checkout $diracTAG
    - cd ..
    # Create a virtual environment in which to run the tests
    - virtualenv DIRAC_VENV
    - source DIRAC_VENV/bin/activate
     # last version supporting python 2
    - pip install 'setuptools<45'
    - pip install --upgrade 'pip<21'
    - pip install -r DIRAC/requirements.txt
    - pip install LbEnv LbPlatformUtils uproot backports.lzma lz4 cx_Oracle==7.3 xmltodict

  stage: test
  only:
    - branches

.test_setup_py3:
  stage: test
  image: registry.cern.ch/docker.io/condaforge/miniforge3:latest
  before_script:
    - eval "$(python -m conda shell.bash hook)"
    - conda install --yes mamba diraccfg git jq
    - lhcbdiracTag=$(cd src && python -c "from LHCbDIRAC import version; print(version)")
    - diracTAG=$(diraccfg as-json src/LHCbDIRAC/releases.cfg | jq -r ".Releases.\"${lhcbdiracTag}\".Depends" | cut -d ':' -f2)
    # - git clone https://github.com/DIRACGrid/DIRAC.git -b "$diracTAG" ../DIRAC
    - git clone https://github.com/chrisburr/DIRAC.git -b "lhcbdirac-fixes" ../DIRAC
    - mamba env create --file ../DIRAC/environment-py3.yml --name test-env
    - conda activate test-env
    - pip install ../DIRAC
    # - pip install .
    - mamba install LbEnv LbPlatformUtils uproot cx_Oracle==7.3 xmltodict

# This runs pylint and fails if there are errors
run_pylint:
  <<: *test_setup
  script:
    - export PYTHONPATH=$(pwd)/DIRAC/src/
    - cd src/LHCbDIRAC
    - 'find . -name "*.py" -and -not -name "NotForJenkins_Test_BKK_DB_OracleBookkeepingDB.py" -exec pylint -E --rcfile=$CI_PROJECT_DIR/DIRAC/.pylintrc --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" --extension-pkg-whitelist=GSI,numpy {} +'

# This runs pytest and generates the coverage report
run_pytest:
  <<: *test_setup
  script:
    - export PYTHONPATH=$(pwd)/DIRAC/src/
    - cd src/LHCbDIRAC
    - DIRAC_DEPRECATED_FAIL=True pytest . --cov=. --cov-report term-missing --cov-report html --junitxml=pytests.xml
  coverage: '/\d+\%\s*$/'
  artifacts:
    paths:
      - LHCbDIRAC/htmlcov/

run_pytest_py3:
  extends: .test_setup_py3
  script:
    - cd src/LHCbDIRAC
    - DIRAC_DEPRECATED_FAIL=True pytest . --cov=. --cov-report term-missing --cov-report html --junitxml=pytests.xml

# This runs pycodestyle
run_pycodestyle:
  <<: *test_setup
  script:
    - lhcbDiracBranch=$(python -c "s = open('src/LHCbDIRAC/releases.cfg').read(); s = s[s.index(' v'):]; s = s.split('\n')[0].strip(); print(s)" | grep -qE '(pre|v0r)'; if [ $? -eq 0 ]; then echo "devel"; else echo "master"; fi)
    - git remote add GL https://gitlab.cern.ch/lhcb-dirac/LHCbDIRAC.git
    - git fetch --no-tags GL
    - git branch -avv
    - git diff -U0 GL/${lhcbDiracBranch}...HEAD | pycodestyle --diff

# Check that the documentation does not generate any error/warning
check_docs:
  #<<: *test_setup
  image:  gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
  before_script:
    - yum install -y openssl mysql mysql-libs mysql-devel make ncurses-devel libcurl-devel swig
    # One has to do it in a virtual env because pip-compile
    # generates a requirements.txt which conflicts with the
    # yum installed python packages (like ipaddress or requests)
    - virtualenv /tmp/generateDoc
    - source /tmp/generateDoc/bin/activate
    - export PYCURL_SSL_LIBRARY=openssl
     # last version supporting python 2
    - pip install 'setuptools<45'
    - pip install --upgrade 'pip<21'
    - pip install pip-tools
  script:
    # We need to use m2crypto, otherwise it looks for GSI, which is annoying
    - export DIRAC_USE_M2CRYPTO=True
    - export PYTHONPATH=$PWD/src
    - cd docs
    # We need to compile the requirements.txt because the crappy pip dependency
    # resolution cannot figure out matplotlib dependency properly
    - mv requirements.txt requirements.in
    - pip-compile requirements.in
    - pip install -r requirements.txt
    # We need to export the DIRAC env variable so that the makefile knows where to find the documentation tools
    - export DIRACDOCTOOLS=$(dirname $(python -c "import diracdoctools; print diracdoctools.__file__"))
    # Remove  numpy from DIRAC_DOC_MOCK_LIST as uproot fails to import without it
    - sed -i "s@'numpy',@@" "${DIRACDOCTOOLS}/__init__.py"
    - SPHINXOPTS=-wsphinxWarnings make htmlall || { echo "Failed to build documentation, check for errors above" ; exit 1; }
    # Check that sphinxWarnings is not empty
    - >
      if [ -s sphinxWarnings ]; then
        echo "********************************************************************************"
        echo "Warnings When Creating Doc:"
        echo "********************************************************************************"
        cat sphinxWarnings
        echo "********************************************************************************"
        exit 1
      fi

# This ensures the license text is present
# Based on: https://gitlab.cern.ch/lhcb/LHCb/blob/master/.gitlab-ci.yml#L14-18
check-copyright:
  stage: test
  before_script:
    - git remote add upstream https://gitlab.cern.ch/lhcb-dirac/LHCbDIRAC.git
    - git fetch --all
    - curl -o lb-check-copyright "https://gitlab.cern.ch/lhcb-core/LbDevTools/raw/master/LbDevTools/SourceTools.py?inline=false"
  script:
    - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - python lb-check-copyright upstream/master --exclude '^tests/.*\.xml$' --exclude 'docs/source.conf.py'

# Integration tests
integration_tests:
  stage: test
  tags:
    - docker-privileged-xl
  image: diracgrid/docker-compose-dirac:latest
  services:
    - docker:19.03.1-dind
  variables:
    # As of GitLab 12.5, privileged runners at CERN mount a /certs/client docker volume that enables use of TLS to
    # communicate with the docker daemon. This avoids a warning about the docker service possibly not starting
    # successfully.
    # See https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_TLS_CERTDIR: "/certs"
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME/LHCbDIRAC
  rules:
    # Using rules causes "Pipelines for Merge Requests" to be triggered, so disable them explicitly
    # https://docs.gitlab.com/ee/ci/merge_request_pipelines/
    - if: '$LHCB_BOOKKEEPING_DB_IMAGE_PASSWORD == null && $CI_MERGE_REQUEST_ID == null'
      allow_failure: true
    - if: '$LHCB_BOOKKEEPING_DB_IMAGE_PASSWORD != null && $CI_MERGE_REQUEST_ID == null'
      allow_failure: false
  before_script:
    - |
      if [[ -z "${LHCB_BOOKKEEPING_DB_IMAGE_PASSWORD:-}" ]]; then
        echo -e '\033[1m\033[31mError LHCB_BOOKKEEPING_DB_IMAGE_PASSWORD variable is not defined!!!\033[0m';
        echo -e 'Due to oracle licensing restrictions CI jobs need a secret to be able able to access the bookkeeping database container.';
        echo -e 'For this test to run you will have to ask another LHCbDIRAC developer to give you access.';
        echo -e "You can then manually copy to a masked variable to your fork's configuration using the instructions at:";
        echo -e ' > https://docs.gitlab.com/ee/ci/variables/#via-the-ui';
        exit 67;
      fi
    # Login to GitLab
    - docker login --username gitlab+deploy-token-794 --password-stdin https://gitlab-registry.cern.ch <<< "${LHCB_BOOKKEEPING_DB_IMAGE_PASSWORD}"
    # Add some dependencies
    - apk add jq python3
    - pip3 install diraccfg
    # diracTAG is the DIRAC tag on top of which the latest LHCbDIRAC release is built in releases.cfg
    - LHCBDIRAC_RELEASE=$(cd src && python3 -c "from LHCbDIRAC import version; print(version)")
    - export LHCBDIRAC_RELEASE
    - diracTAG=$(diraccfg as-json src/LHCbDIRAC/releases.cfg | jq -r ".Releases.\"${LHCBDIRAC_RELEASE}\".Depends" | cut -d ':' -f2)
    - diracRef="rel-$(echo "${diracTAG}" | cut -d 'p' -f1)"
    - cd $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME
    # Get DIRAC
    - git clone https://github.com/DIRACGrid/DIRAC.git
    - cd DIRAC
    #- git checkout "$diracRef" there is no branch with name rel-v7r2 currently
    - git checkout integration
    - cd ..
    # Environment
    - export DIRAC_CI_SETUP_SCRIPT=LHCbDIRAC/tests/Jenkins/lhcb_ci.sh
    - export DIRACOSVER=LHCb:master
    - export DIRACBRANCH=${LHCBDIRAC_RELEASE}
    - export CI_REGISTRY_IMAGE=diracgrid
    # ALTERNATIVE_MODULES
    - declare -a ALTERNATIVE_MODULES
    - ALTERNATIVE_MODULES+=("$PWD/LHCbDIRAC/src/LHCbDIRAC")
    - ALTERNATIVE_MODULES+=("$PWD/DIRAC/src/DIRAC")
    # TESTREPO
    - declare -a TESTREPO
    - TESTREPO+=("$PWD/LHCbDIRAC")
    - TESTREPO+=("$PWD/DIRAC")
    # EXTRA_ENVIRONMENT_CONFIG
    - declare -a EXTRA_ENVIRONMENT_CONFIG
    - EXTRA_ENVIRONMENT_CONFIG+=("export LHCBDIRAC_RELEASE=${LHCBDIRAC_RELEASE}")
    # INSTALLOPTIONS
    - declare -a INSTALLOPTIONS
    - INSTALLOPTIONS+=("-l" "LHCb" "-e" "LHCb")
    # Start the bookkeeping database container
    - |
      docker run --rm --detach --name bkdb \
        -p 1521:1521 \
        -e ORACLE_SID=bkdbsid \
        -e ORACLE_PDB=bkdbpdb \
        -e ORACLE_PWD=bkdbpass \
        -e ORACLE_CHARACTERSET=AL32UTF8 \
        -v $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_NAME:/repo \
        gitlab-registry.cern.ch/lhcb-dirac/bookkeeping-ci-container/oracle-database-snapshots:19.3.0-ee
  script:
    - source DIRAC/tests/CI/run_docker_setup.sh
    - prepareEnvironment
    # Install oracle client (will only work inside the CERN network!)
    - docker exec -w /home/dirac server yum-config-manager --add-repo http://linuxsoft.cern.ch//cern/centos/7/cernonly/x86_64
    - docker exec -w /home/dirac server yum install -y oracle-instantclient-basic oracle-instantclient-devel
    # Finish configuring the bokkeeping database
    - docker network connect ci_default bkdb
    - |
      while ! (docker logs bkdb | grep 'DATABASE IS READY TO USE!'); do
        echo "Waiting for bookkeeping database to be ready... $(docker logs bkdb | grep 'complete' | tail -n 1)";
        sleep 15;
      done
    - docker exec bkdb bash -x /repo/LHCbDIRAC/tests/Jenkins/bookkeeping_install/setup_ci_bookkeeping_db.sh
    # Carry on with the CI as normal
    - installServer
    - installClient
    - testServer
    - testClient
    - checkErrors

### coverage stage ###

# This job MUST be call pages as per https://docs.gitlab.com/ce/ci/yaml/README.html#pages
pages:
  stage: coverage
  dependencies:
    - run_pytest
  script:
    - TARGET_DIR="public/${CI_COMMIT_REF_NAME}"
    - if [ ! -d "$TARGET_DIR" ]; then mkdir -p $TARGET_DIR; fi
    - echo "Copying into $TARGET_DIR"
    - mv LHCbDIRAC/htmlcov/* $TARGET_DIR
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master@lhcb-dirac/LHCbDIRAC
    - devel@lhcb-dirac/LHCbDIRAC

# Deploy the pages generated to DFS
dfsdeploy:
  # Executed during the deploy stage
  stage: coverageDfs
  # # Only when the master branch is pushed
  only:
    - master
    - devel
  # Custom docker image providing the needed tools to deploy in DFS
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  script:
  # Script that performs the deploy to DFS. Makes use of the variables defined in the project
  # It will not sync the generated content with the folder in DFS (risk of deleting DFS management files)
  # It will just override the contents of DFS or copy new files
  - deploy-dfs
  # do not run any globally defined before_script or after_script for this step
  before_script: []
  after_script: []


# ### release stage ###

# This creates and deploy the tarball
# It is triggered with a tag only
create_tarball:
  image: diracgrid/dirac-distribution:latest
  before_script:
    # Fetch a Kerberos token
    - echo "${KRB_PASSWORD}" | kinit ${KRB_USERNAME}@CERN.CH
    - apt-get install -y curl
  stage: release
  only:
    - tags@lhcb-dirac/LHCbDIRAC
  variables:
    GIT_STRATEGY: none
  script:
    # Choose from which branch we should get the releases.cfg file
    # We take it from devel if it is a pre release, otherwise master
    - BRANCH=$(echo ${CI_COMMIT_TAG} | grep -qE '^v[1-9][0-9]*r[0-9]+(p[0-9]+)?$'; if [ $? -eq 0 ]; then echo "master"; else echo "devel"; fi)
    # Get the releases.cfg from the appropriate branch
    - curl -O -L https://gitlab.cern.ch/lhcb-dirac/LHCbDIRAC/raw/$BRANCH/LHCbDIRAC/releases.cfg
    # - curl -O -L https://gitlab.cern.ch/lhcb-dirac/LHCbDIRAC/raw/$BRANCH/src/LHCbDIRAC/releases.cfg
    # Create the release tarball
    # The last line output by the script is the command to run in order to deploy
    - python3 /dirac-distribution.py -r ${CI_COMMIT_TAG} -l LHCb -C file:///$(pwd)/releases.cfg | tail -n 1  > /tmp/deploy.sh
    - cat /tmp/deploy.sh
    - export USER=${KRB_USERNAME}
    - source /tmp/deploy.sh


# ### deploy_release stage ###

# When we have a git tag, after creating the tarball, create a docker image used by Mesos
# and upload it to the gitlab registry
build_docker_image:
  stage: deploy_release
  only:
    - tags
  image:
    name: gitlab-registry.cern.ch/ci-tools/docker-image-builder
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/container/lhcbdirac --dockerfile $CI_PROJECT_DIR/container/lhcbdirac/Dockerfile --destination $CI_REGISTRY_IMAGE:${CI_COMMIT_TAG}


# This instead creates a docker image to be used as LHCbDIRAC client
build_client_docker_image:
  stage: deploy_release
  allow_failure: true
  only:
    - tags
  image:
    name: gitlab-registry.cern.ch/ci-tools/docker-image-builder
    entrypoint: [""]
  script:
    # Replacements
    - sed -i "s %%LHCB_DIRAC_VERSION%% $CI_COMMIT_TAG g" ./container/client/Dockerfile
    - SETUP=$(echo $CI_COMMIT_TAG | grep -qE '(pre|^v0r)'; if [ $? -eq 0 ]; then echo "LHCb-Certification"; else echo "LHCb-Production"; fi)
    - sed -i "s %%LHCB_DIRAC_SETUP%% $SETUP g" ./container/client/Dockerfile
    - CS=$(echo $CI_COMMIT_TAG | grep -qE '(pre|^v0r)'; if [ $? -eq 0 ]; then echo "dips://lhcb-cert-conf-dirac.cern.ch:9135/Configuration/Server"; else echo "dips://lbvobox100.cern.ch:9135/Configuration/Server,dips://lbvobox102.cern.ch:9135/Configuration/Server,dips://lbvobox103.cern.ch:9135/Configuration/Server,dips://lbvobox104.cern.ch:9135/Configuration/Server"; fi)
    - sed -i "s %%LHCB_DIRAC_CS%% $CS g" ./container/client/Dockerfile
    # Now build and upload to GitLab registry
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/container/client --dockerfile $CI_PROJECT_DIR/container/client/Dockerfile --destination $CI_REGISTRY_IMAGE:client-${CI_COMMIT_TAG}
    # Upload to Docker Hub - with no kaniko
    # FIXME: this fails as there's no docker installed...
    # - echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin
    # - docker push diracgrid/lhcbdirac:${CI_COMMIT_TAG}

# Template job used by deploy_on_cvmfs and set_cvmfs_prod_link
.cvmfs_task:
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /v\d+r.+/
  before_script:
    - |
      if [[ "${CI_COMMIT_TAG}" == *"-pre"* ]]; then
        LHCB_DIRAC_SETUP="LHCb-Certification"
      else
        LHCB_DIRAC_SETUP="LHCb-Production"
      fi


# Deploy the release on CVMFS but don't set the prod symlink
deploy_on_cvmfs:
  extends: .cvmfs_task
  stage: deploy_release
  script:
    - ./.ci/trigger_cvmfs_deployment.sh deploy "${LHCB_DIRAC_SETUP}" "${CI_COMMIT_TAG}"


# ### update instance stage ###
# Template job used to get lhcb_admin proxy for production or certification
.getAdminProxy:
  tags:
    - docker
    - cvmfs
  only:
    - tags@lhcb-dirac/LHCbDIRAC
  image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
  before_script:
    - mkdir -p ~/.globus
    - echo "$BOT_USERCERT_PEM" | tr -d '\r' > ~/.globus/usercert.pem
    - echo "$BOT_USERKEY_PEM" | tr -d '\r' > ~/.globus/userkey.pem
    - chmod 400 ~/.globus/userkey.pem
    - chmod 644  ~/.globus/usercert.pem
    - INSTANCE=$(echo ${CI_COMMIT_TAG} | grep -qE '^v[1-9][0-9]*r[0-9]+(p[0-9]+)?$'; if [ $? -eq 0 ]; then echo "lhcb.cern.ch"; else echo "lhcbdev.cern.ch"; fi)
    - echo "Using LHCbDIRAC installation from /cvmfs/${INSTANCE}/lhcbdirac/"
    - source /cvmfs/${INSTANCE}/lhcbdirac/bashrc
    - lhcb-proxy-init -g lhcb_admin <<< $BOT_CERT_PASSPHRASE

update_instance:
  extends: .getAdminProxy
  when: manual
  stage: update
  script:
    - |
      if [ ! -L "/cvmfs/${INSTANCE}/lhcbdirac/${CI_COMMIT_TAG}" ]; then
       echo "New version not found in CVMFS"
       exit 1
      fi
    - |
      if [[ "${INSTANCE}" == "lhcb.cern.ch" ]]; then
        dirac-admin-sysadmin-cli <<< "show hosts" | awk '{print $2}' | grep -E "(\..*){2}" > allHosts.txt
        grep ".cern.ch" allHosts.txt > primaryHosts.txt
        grep -v ".cern.ch" allHosts.txt > secondaryHosts.txt
        dirac-admin-update-instance ${CI_COMMIT_TAG} --retry=2 --hosts=secondaryHosts.txt || echo "Allow failure"
        dirac-admin-update-instance ${CI_COMMIT_TAG} --retry=2 --hosts=primaryHosts.txt
      else
        dirac-admin-update-instance ${CI_COMMIT_TAG} --retry=2
      fi
    - dirac-admin-update-pilot ${CI_COMMIT_TAG}


# ### finish_up stage ###

# If we are triggering on a pre release,
# tag the docker image we just built as 'devel'
# check https://gitlab.cern.ch/ci-tools/docker-image-tools for the image doc
add_devel_tag:
  image: gitlab-registry.cern.ch/ci-tools/docker-image-tools:add-tag
  stage: finish_up
  script:
  - 'Adding tag...'
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /.*-pre.*/
  variables:
    DOCKER_IMAGE_PATH: $CI_REGISTRY_IMAGE
    OLDTAG: ${CI_COMMIT_TAG}
    NEWTAG: devel
    GIT_STRATEGY: none

# Use a manual job to change the version of the prod symlink
# This task can be ran multiple times which means an old pipeline can be restarted to roll back the prod symlink
set_cvmfs_prod_link:
  extends: .cvmfs_task
  stage: finish_up
  when: manual
  script:
    - ./.ci/trigger_cvmfs_deployment.sh set-prod "${LHCB_DIRAC_SETUP}" "${CI_COMMIT_TAG}"

# Job for starting the tag procedure
make_tag:
  stage: tag
  when: manual
  tags:
    - docker
  variables:
    GIT_STRATEGY: none
  image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
  # Can be run only on master and devel branch of the main repo
  only:
    refs:
      - master@lhcb-dirac/LHCbDIRAC
      - devel@lhcb-dirac/LHCbDIRAC
  except:
    - tags
  before_script:
    # Remeind the user if he set the variables for versions
    - if [ -z ${DIRAC+x} ]; then echo "variable DIRAC is unset, using the same version as previous release"; else echo "You are targeting DIRAC version ${DIRAC}"; fi
    - if [ -z ${LHCbDIRACOS+x} ]; then echo "variable LHCbDIRACOS is unset, using the same version as previous release"; else echo "You are targeting LHCbDIRACOS version ${LHCbDIRACOS}"; fi
    - if [ -z ${LHCbWebDIRAC+x} ]; then echo "variable LHCbWebDIRAC is unset, using the same version as previous release"; else echo "You are targeting LHCbWebDIRAC version ${LHCbWebDIRAC}"; fi
    - yum install python3 jq git -y
    - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    - python3 get-pip.py
    - pip3 install -U requests python-dateutil pytz diraccfg
    # Get the tagging tool from the DIRACGrid repo
    - curl -O https://raw.githubusercontent.com/DIRACGrid/DIRAC/integration/docs/diracdoctools/scripts/dirac-docs-get-release-notes.py
    - rm -f releases.cfg
    # Get the master version of the releases.cfg from the LHCbDIRAC main repo devel branch
    - curl -O https://gitlab.cern.ch/lhcb-dirac/LHCbDIRAC/-/raw/devel/LHCbDIRAC/releases.cfg
    # - curl -O https://gitlab.cern.ch/lhcb-dirac/LHCbDIRAC/-/raw/devel/src/LHCbDIRAC/releases.cfg
    # init the dirac bot gitlab user
    - eval `ssh-agent -s`
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KEY" | tr -d '\r' > /root/.ssh/id_rsa
    - chmod 700 /root/.ssh/id_rsa
    - ssh-keyscan -p 7999 gitlab.cern.ch >> /root/.ssh/known_hosts
    - git config --global user.email "dirac.bot@cern.ch"
    - git config --global user.name "LHCbDIRAC Bot"
    - git config --global pull.rebase true
  script:
    - echo "GITLABTOKEN = \"$GITLABTOKEN\"" >& GitTokens.py
    # Aggregate the release notes for the current branch
    - python3 dirac-docs-get-release-notes.py --sinceLatestTag -g  -i 3588 --branches ${CI_COMMIT_REF_NAME} | sed '1,2d'>& notes.txt
    # set LATEST_RELEASE variable depending on the branch
    - if [[ "${CI_COMMIT_REF_NAME}" == "master" ]]; then export LATEST_RELEASE=`diraccfg as-json releases.cfg | jq '.Releases' | diraccfg sort-versions | jq -r '.[0]'` ; fi
    - if [[ "${CI_COMMIT_REF_NAME}" == "devel" ]];  then export LATEST_RELEASE=`diraccfg as-json releases.cfg | jq '.Releases' | diraccfg sort-versions --allow-pre-releases | jq -r '.[0]'` ; fi
    - echo "The latest release of LHCbDIRAC is ${LATEST_RELEASE}"
    # remove potential folder coming from artifacts
    - rm -rf LHCbDIRAC
    # checkout the repo
    - git clone ssh://git@gitlab.cern.ch:7999/lhcb-dirac/LHCbDIRAC.git LHCbDIRAC
    - cd src/LHCbDIRAC
    # checkout the correct branch we can only be on master or devel
    - git checkout ${CI_COMMIT_REF_NAME}
    # get the last releases.cfg
    - mv ../releases.cfg releases.cfg
    # Call the python script that generated all the artifacts for the release
    - python3 tests/Utilities/createReleaseFiles.py
    - mv releases.cfg src/LHCbDIRAC/releases.cfg
    - export SERIES=`cat series.txt`
    - export VERSION=`cat version.txt`
    # insert new release notes into the changelog
    - cat ../notes.txt CHANGELOG/$SERIES > newNotes.txt
    - mv newNotes.txt CHANGELOG/$SERIES
    # show all the changes we have done
    - cp CHANGELOG/$SERIES ../changes.txt
    - cp src/LHCbDIRAC/releases.cfg ../releases.cfg
    - git diff
    - git add -u
    # commit all the changes to the current branch
    - git commit -av -m "Update versions and changelog for release of ${VERSION}"
    # tag current branch
    - git tag -a ${VERSION} -m ${VERSION}
    # push commits and tag to main repo back
    - git push --tags origin ${CI_COMMIT_REF_NAME}
    # If we just tagged master we need to update also the releases.cfg and CHANGELOG in devel
    # Checkout devel and apply the changes
    - git fetch origin
    - git checkout devel
    - git reset --hard origin/devel
    - cp ../changes.txt CHANGELOG/$SERIES
    - cp ../releases.cfg src/LHCbDIRAC/releases.cfg
    # Only push this changes to devel if master was tagged. Don't push if you tagged devel
    - if [[ "${CI_COMMIT_REF_NAME}" == "master" ]]; then git commit -av -m "Add release ${VERSION} to releases.cfg and CHANGELOG"  ; fi
    - if [[ "${CI_COMMIT_REF_NAME}" == "master" ]]; then git push origin devel ; fi
    - cd ../..
    # Create release in gitlab
    - echo "GITLABTOKEN = \"$GITLABTOKEN\"" >& GitTokens.py
    - python3 dirac-docs-get-release-notes.py -g -i 3588 --tagName ${VERSION} --releaseNotes notes.txt --deployRelease
