name: Integration tests

on: [push, pull_request]

jobs:
  Integration:
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || github.repository == 'DIRACGrid/DIRAC'
    timeout-minutes: 45
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: False
      matrix:
        # TEST_NAME is a dummy variable used to make it easier to read the web interface
        include:
          ###### MySQL versions
          - TEST_NAME: "MySQL 5.7"
            ARGS: CLIENT_USE_PYTHON3=Yes MYSQL_VER=mysql:5.7
          - TEST_NAME: "MariaDB 10.6"
            ARGS: CLIENT_USE_PYTHON3=Yes MYSQL_VER=mariadb:10.6.3
          # ###### ES versions
          - TEST_NAME: "Elasticsearch 6.6.0"
            ARGS: CLIENT_USE_PYTHON3=Yes ES_VER=elasticsearch:6.6.0
          - TEST_NAME: "OpenSearch 1.0.0"
            ARGS: CLIENT_USE_PYTHON3=Yes ES_VER=opensearchproject/opensearch:1.0.0
          ###### Fewer cfg locks
          - TEST_NAME: "Fewer cfg locks"
            ARGS: CLIENT_USE_PYTHON3=Yes DIRAC_FEWER_CFG_LOCKS=Yes
          ###### HTTPS tests
          - TEST_NAME: "HTTPS"
            ARGS: CLIENT_USE_PYTHON3=Yes TEST_HTTPS=Yes
          - TEST_NAME: "Py3 client, py3 server + HTTPS"
            ARGS: CLIENT_USE_PYTHON3=Yes SERVER_USE_PYTHON3=Yes TEST_HTTPS=Yes
          ###### Python 2
          - TEST_NAME: "Py2 client, py3 server"
            ARGS: SERVER_USE_PYTHON3=Yes
          - TEST_NAME: "Py2 client, py2 server"
          - TEST_NAME: "Py2 client, py3 server+HTTPS"
            ARGS: SERVER_USE_PYTHON3=Yes TEST_HTTPS=Yes

    steps:
    - uses: actions/checkout@v2
    - name: Fail-fast for outdated pipelines
      run: .github/workflows/fail-fast.sh
    - run: |
        git fetch --prune --unshallow
    - uses: conda-incubator/setup-miniconda@master
      with:
        environment-file: environment-py3.yml
        miniforge-variant: Mambaforge
        use-mamba: true
    - name: Prepare environment
      run: ./integration_tests.py prepare-environment ${{ matrix.ARGS }}
    - name: Install server
      run: ./integration_tests.py install-server
    - name: Install client
      run: ./integration_tests.py install-client
    - name: Server tests
      run: ./integration_tests.py test-server || touch server-tests-failed
    - name: Client tests
      run: ./integration_tests.py test-client || touch client-tests-failed
    - name: Elasticsearch logs
      run: docker logs elasticsearch
    - name: Check test status
      run: |
        has_error=0
        if [ -f server-tests-failed ]; then has_error=1; echo "Server tests failed"; fi
        if [ -f client-tests-failed ]; then has_error=1; echo "Client tests failed"; fi
        if [ ${has_error} = 1 ]; then exit 1; fi
